 <div class="buttons">
               <input type="submit" name="delete_button" value="Delete Selected">
                <select name="status" id="select-status">
                    <option value="">Status change selection</option>
                    <option value="new">New</option>
                    <option value="current">Current</option>
                    <option value="final">Final</option>
                </select>
                <input type="submit" name="status_button" value="Change Status"> 
            </div>