    <footer>
      <img src="images/Logo_trademark.png" alt="Logo design in circle" />
      <h2>Contact Us</h2>
      <p>Phone No.: 1800 671 829</p>
      <p>Email: Queries@Softwareengineeringassociation.com.at</p>
      <p>Company HQ Address: Bikini Bottom, Atlantis, Unspacific ocean</p>
      <p>Trademark</p>
     <a href="https://student-team-a3yg1sga.atlassian.net/jira/software/projects/SWTP/boards/2/backlog?epics=visible&atlOrigin=eyJpIjoiMzhkYTIxMWE4MzNmNDUzNWEyYmZiMmNlNzk1NmM5OWEiLCJwIjoiaiJ9"
      target="_blank"
     >
      JIRA Project
      </a>
    </footer>