<thead>
    <tr>
        <th>Select</th>
        <th>EOInumber</th>
        <th>Reference No.</th> 
        <th>First name</th>
        <th>Last name</th>
        <th>DOB</th>
        <th>Gender</th>
        <th>Street Address</th>
        <th>Suburb</th>
        <th>State</th>
        <th>Postcode</th>
        <th>Email</th>
        <th>Phone</th>
        <th>Skills</th>
        <th>ENUM</th>
    </tr>
</thead>